name: Continuous Integration
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Configure
      - uses: actions/checkout@v1
        run: ./configure
          shell: bash

      - name: Compile
        run: make
          shell: bash
