name: Build and test
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [2.7, 3.7]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Install autotools on macOS
        if: matrix.os == 'macOS-latest'
        run: brew install automake autoconf libtool

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Bootstrap build environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
        shell: bash
        run: ./bootstrap.sh

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cffi sklearn catboost

      - name: Configure source code
        shell: bash
        run: ./configure

      - name: Compile source code
        shell: bash
        run: make

      - name: Run unit tests
        run: python bindings/python/setup.py test

      - name: Run example
        run: python bindings/python/example.py
