name: Build and test
on: push
jobs:
  msys2-python3:
    strategy:
      matrix:
        os: [windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: |
          choco install -y msys2

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Build
        shell: bash
        run: ./bootstrap.sh
