name: Continuous Integration
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Configure
      - shell: bash
        run: ./configure

      - name: Compile
      - shell: bash
        run: make
