name: Build and test
on: push
jobs:
  msys2-python3:
    strategy:
      matrix:
        os: [windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install MSYS2
        run: choco install -y msys2 --params "/NoUpdate"

      - name: Install autotools
        shell: C:\tools\msys64\usr\bin\bash.exe --login {0}
        run: pacman -S automake autoconf libtool

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Build
        shell: C:\tools\msys64\usr\bin\bash.exe --login {0}
        run: ./bootstrap.sh
