name: Continuous Integration
on: [push]
jobs:
  macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install (optional) python dependencies
        run: python -m pip install cffi sklearn catboost
  
      - name: Configure
        run: bash ./configure

      - name: Compile
        run: make

      - name: Unit Test
        run: python bindings/python/setup.py test

      - name: Run Example
        run: python bindings/python/example.py

