name: Build and test
on: push
jobs:
  ubuntu-python2:
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install autoconf libtool build-essential
          sudo apt-get install python-cffi python-pip python-sklearn
          python2 -m pip install catboost --user

      - name: Build
        run: |
          ./bootstrap.sh
          PYTHON=python2 ./configure
          make

      - name: Test
        run: |
          python2 bindings/python/example.py
          python2 bindings/python/setup.py test
